//go:build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto copies all properties of WorkloadOutcome into another instance.
func (in *WorkloadOutcome) DeepCopyInto(out *WorkloadOutcome) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

func (in *WorkloadOutcome) DeepCopy() *WorkloadOutcome {
	if in == nil {
		return nil
	}
	out := new(WorkloadOutcome)
	in.DeepCopyInto(out)
	return out
}

func (in *WorkloadOutcome) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *WorkloadOutcomeList) DeepCopyInto(out *WorkloadOutcomeList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]WorkloadOutcome, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

func (in *WorkloadOutcomeList) DeepCopy() *WorkloadOutcomeList {
	if in == nil {
		return nil
	}
	out := new(WorkloadOutcomeList)
	in.DeepCopyInto(out)
	return out
}

func (in *WorkloadOutcomeList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *WorkloadOutcomeSpec) DeepCopyInto(out *WorkloadOutcomeSpec) {
	*out = *in
	out.TargetRef = in.TargetRef
	in.SLO.DeepCopyInto(&out.SLO)
	if in.Cost != nil {
		in, out := &in.Cost, &out.Cost
		*out = new(CostSpec)
		**out = **in
	}
	if in.Compliance != nil {
		in, out := &in.Compliance, &out.Compliance
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

func (in *WorkloadOutcomeSpec) DeepCopy() *WorkloadOutcomeSpec {
	if in == nil {
		return nil
	}
	out := new(WorkloadOutcomeSpec)
	in.DeepCopyInto(out)
	return out
}

func (in *SLOSpec) DeepCopyInto(out *SLOSpec) {
	*out = *in
	if in.LatencyP99Ms != nil {
		in, out := &in.LatencyP99Ms, &out.LatencyP99Ms
		*out = new(int32)
		**out = **in
	}
	if in.LatencyP95Ms != nil {
		in, out := &in.LatencyP95Ms, &out.LatencyP95Ms
		*out = new(int32)
		**out = **in
	}
	if in.ThroughputRPS != nil {
		in, out := &in.ThroughputRPS, &out.ThroughputRPS
		*out = new(int32)
		**out = **in
	}
}

func (in *SLOSpec) DeepCopy() *SLOSpec {
	if in == nil {
		return nil
	}
	out := new(SLOSpec)
	in.DeepCopyInto(out)
	return out
}

func (in *CostSpec) DeepCopyInto(out *CostSpec) { *out = *in }
func (in *CostSpec) DeepCopy() *CostSpec {
	if in == nil {
		return nil
	}
	out := new(CostSpec)
	in.DeepCopyInto(out)
	return out
}

func (in *WorkloadRef) DeepCopyInto(out *WorkloadRef) { *out = *in }

func (in *WorkloadOutcomeStatus) DeepCopyInto(out *WorkloadOutcomeStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.DerivedConfigRef != nil {
		in, out := &in.DerivedConfigRef, &out.DerivedConfigRef
		*out = new(ConfigRef)
		**out = **in
	}
	if in.LastReconciledAt != nil {
		in, out := &in.LastReconciledAt, &out.LastReconciledAt
		*out = (*in).DeepCopy()
	}
	if in.SLOViolations != nil {
		in, out := &in.SLOViolations, &out.SLOViolations
		*out = make([]SLOViolation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.AgentDecisions != nil {
		in, out := &in.AgentDecisions, &out.AgentDecisions
		*out = make([]AgentDecision, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

func (in *WorkloadOutcomeStatus) DeepCopy() *WorkloadOutcomeStatus {
	if in == nil {
		return nil
	}
	out := new(WorkloadOutcomeStatus)
	in.DeepCopyInto(out)
	return out
}

func (in *SLOViolation) DeepCopyInto(out *SLOViolation) {
	*out = *in
	in.DetectedAt.DeepCopyInto(&out.DetectedAt)
}
func (in *SLOViolation) DeepCopy() *SLOViolation {
	if in == nil {
		return nil
	}
	out := new(SLOViolation)
	in.DeepCopyInto(out)
	return out
}

func (in *AgentDecision) DeepCopyInto(out *AgentDecision) {
	*out = *in
	in.Timestamp.DeepCopyInto(&out.Timestamp)
}
func (in *AgentDecision) DeepCopy() *AgentDecision {
	if in == nil {
		return nil
	}
	out := new(AgentDecision)
	in.DeepCopyInto(out)
	return out
}

func (in *ConfigRef) DeepCopyInto(out *ConfigRef) { *out = *in }

// ClusterForecast deep copy methods

func (in *ClusterForecast) DeepCopyInto(out *ClusterForecast) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

func (in *ClusterForecast) DeepCopy() *ClusterForecast {
	if in == nil {
		return nil
	}
	out := new(ClusterForecast)
	in.DeepCopyInto(out)
	return out
}

func (in *ClusterForecast) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *ClusterForecastList) DeepCopyInto(out *ClusterForecastList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ClusterForecast, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

func (in *ClusterForecastList) DeepCopy() *ClusterForecastList {
	if in == nil {
		return nil
	}
	out := new(ClusterForecastList)
	in.DeepCopyInto(out)
	return out
}

func (in *ClusterForecastList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *ClusterForecastSpec) DeepCopyInto(out *ClusterForecastSpec) {
	*out = *in
	if in.WorkloadSelectors != nil {
		in, out := &in.WorkloadSelectors, &out.WorkloadSelectors
		*out = make([]WorkloadSelector, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

func (in *ClusterForecastSpec) DeepCopy() *ClusterForecastSpec {
	if in == nil {
		return nil
	}
	out := new(ClusterForecastSpec)
	in.DeepCopyInto(out)
	return out
}

func (in *WorkloadSelector) DeepCopyInto(out *WorkloadSelector) {
	*out = *in
	if in.LabelSelector != nil {
		in, out := &in.LabelSelector, &out.LabelSelector
		*out = (*in).DeepCopy()
	}
}

func (in *ClusterForecastStatus) DeepCopyInto(out *ClusterForecastStatus) {
	*out = *in
	if in.Forecasts != nil {
		in, out := &in.Forecasts, &out.Forecasts
		*out = make([]WorkloadForecast, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.LastUpdated != nil {
		in, out := &in.LastUpdated, &out.LastUpdated
		*out = (*in).DeepCopy()
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

func (in *ClusterForecastStatus) DeepCopy() *ClusterForecastStatus {
	if in == nil {
		return nil
	}
	out := new(ClusterForecastStatus)
	in.DeepCopyInto(out)
	return out
}

func (in *WorkloadForecast) DeepCopyInto(out *WorkloadForecast) {
	*out = *in
	if in.PredictedEvents != nil {
		in, out := &in.PredictedEvents, &out.PredictedEvents
		*out = make([]PredictedEvent, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.RecommendedActions != nil {
		in, out := &in.RecommendedActions, &out.RecommendedActions
		*out = make([]RecommendedAction, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.ResourceForecast != nil {
		in, out := &in.ResourceForecast, &out.ResourceForecast
		*out = make([]ResourcePoint, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

func (in *PredictedEvent) DeepCopyInto(out *PredictedEvent) {
	*out = *in
	in.PredictedAt.DeepCopyInto(&out.PredictedAt)
	if in.SupportingEvidence != nil {
		in, out := &in.SupportingEvidence, &out.SupportingEvidence
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

func (in *RecommendedAction) DeepCopyInto(out *RecommendedAction) {
	*out = *in
	in.ScheduledFor.DeepCopyInto(&out.ScheduledFor)
}

func (in *ResourcePoint) DeepCopyInto(out *ResourcePoint) {
	*out = *in
	in.Time.DeepCopyInto(&out.Time)
}

// OutcomeBinding deep copy methods

func (in *OutcomeBinding) DeepCopyInto(out *OutcomeBinding) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

func (in *OutcomeBinding) DeepCopy() *OutcomeBinding {
	if in == nil {
		return nil
	}
	out := new(OutcomeBinding)
	in.DeepCopyInto(out)
	return out
}

func (in *OutcomeBinding) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *OutcomeBindingList) DeepCopyInto(out *OutcomeBindingList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]OutcomeBinding, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

func (in *OutcomeBindingList) DeepCopy() *OutcomeBindingList {
	if in == nil {
		return nil
	}
	out := new(OutcomeBindingList)
	in.DeepCopyInto(out)
	return out
}

func (in *OutcomeBindingList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *OutcomeBindingSpec) DeepCopyInto(out *OutcomeBindingSpec) {
	*out = *in
	out.OutcomeRef = in.OutcomeRef
	out.TargetRef = in.TargetRef
	if in.ChangeWindow != nil {
		in, out := &in.ChangeWindow, &out.ChangeWindow
		*out = new(ChangeWindowSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.RollbackPolicy != nil {
		in, out := &in.RollbackPolicy, &out.RollbackPolicy
		*out = new(RollbackPolicySpec)
		**out = **in
	}
}

func (in *OutcomeBindingSpec) DeepCopy() *OutcomeBindingSpec {
	if in == nil {
		return nil
	}
	out := new(OutcomeBindingSpec)
	in.DeepCopyInto(out)
	return out
}

func (in *ChangeWindowSpec) DeepCopyInto(out *ChangeWindowSpec) {
	*out = *in
	if in.AllowedDays != nil {
		in, out := &in.AllowedDays, &out.AllowedDays
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

func (in *OutcomeBindingStatus) DeepCopyInto(out *OutcomeBindingStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.LastAppliedAt != nil {
		in, out := &in.LastAppliedAt, &out.LastAppliedAt
		*out = (*in).DeepCopy()
	}
	if in.PendingProposalRef != nil {
		in, out := &in.PendingProposalRef, &out.PendingProposalRef
		*out = new(corev1ObjectReference)
		**out = **in
	}
	if in.RollbackHistory != nil {
		in, out := &in.RollbackHistory, &out.RollbackHistory
		*out = make([]RollbackEvent, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

func (in *RollbackEvent) DeepCopyInto(out *RollbackEvent) {
	*out = *in
	in.Timestamp.DeepCopyInto(&out.Timestamp)
}

// type aliases to avoid import cycle in generated code
type v1Condition = metav1Condition
type corev1ObjectReference = objectReference
